name: Pull Request Checker
on:
  pull_request:
    branches:
      - master
  branches:
    

runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [ubuntu-latest, osx, windows]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install dependencies
      run: sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libsdl2-dev libasound2-dev
      if:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl matrix https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
